### PR TITLE
fix: do not add link if the target type is null

### LINKED ISSUE #29: Recipe failing with NPE at "addLink"
Stack trace : 

```
Execution failed for task ':serveur:rewriteRun'.
> java.lang.RuntimeException: Error while visiting XXXXX OBFSUCATED DATA XXXXXXX\EvaluationExpressionServiceTU.java: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JavaType$FullyQualified.getPackageName()" because "targetType" is null
    io.github.jtama.openrewrite.ProjectAerialViewGenerator$1.lambda$addLink$1(ProjectAerialViewGenerator.java:174)
    java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
    java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
    java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
    java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
    java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
    java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
    java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
    java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    java.base/java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:642)
    io.github.jtama.openrewrite.ProjectAerialViewGenerator$1.addLink(ProjectAerialViewGenerator.java:174)
    io.github.jtama.openrewrite.ProjectAerialViewGenerator$1.visitFieldAccess(ProjectAerialViewGenerator.java:151)
    io.github.jtama.openrewrite.ProjectAerialViewGenerator$1.visitFieldAccess(ProjectAerialViewGenerator.java:100)
    org.openrewrite.java.tree.J$FieldAccess.acceptJava(J.java:2099)
    org.openrewrite.java.tree.J.accept(J.java:55)
    ...
```

Visited java source file : 

```java
package XXXXX OBFSUCATED DATA XXXXXXX;

import io.quarkus.test.component.QuarkusComponentTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@QuarkusComponentTest
@ExtendWith(MockitoExtension.class)
public class EvaluationExpressionServiceTU {

    @Inject
    EvaluationExpressionService evaluationExpressionServiceservice;

    private final static String cheminParDefaut = "cleTest.sousCleTest";

    private Map<String, Map<String, Object>> construireMapInitiale(Object data) {
        return Map.of("cleTest", Map.of("sousCleTest", data));
    }

    @Test
    void test_evaluerCondition() {
        // Arrange
        boolean condition = true;
        Map<String, Map<String, Object>> data = construireMapInitiale(condition);

        // Act
        boolean evaluation = evaluationExpressionServiceservice.evaluerCondition(cheminParDefaut, data);

        // Arrange
        assertTrue(evaluation);
    }

    @Test
    void test_evaluerMap() {
        // Arrange
        String cleCible = "cleCible";
        Map<String, String> mapCible = Map.of(cleCible, "test");
        Map<String, Map<String, Object>> data = construireMapInitiale(mapCible);

        // Act
        Map<String, Object> evaluation = evaluationExpressionServiceservice.evaluerMap(cheminParDefaut, data);

        // Assert
        assertNotNull(evaluation);
        assertTrue(evaluation.containsKey(cleCible));
        assertEquals("test", evaluation.get(cleCible));
    }

    @Test
    void test_evaluerListe() {
        // Arrange
        List<String> listeCible = List.of("test");
        Map<String, Map<String, Object>> data = construireMapInitiale(listeCible);

        // Act
        List<String> evaluation = evaluationExpressionServiceservice.evaluerListe(cheminParDefaut, data);

        // Assert
        assertNotNull(evaluation);
        assertEquals(1, evaluation.size());
        assertEquals("test", evaluation.getFirst());
    }

    @Test
    void test_evaluerObject() {
        // Arrange
        int objet = 1;
        Map<String, Map<String, Object>> data = construireMapInitiale(objet);

        // Act
        int evaluation = evaluationExpressionServiceservice.evaluerObjet(cheminParDefaut, data, int.class);

        // Assert
        assertEquals(1, evaluation);
    }

    @Test
    void test_evaluerStringSiExpression() {
        // Arrange
        String expression = "§§{%s}".formatted(cheminParDefaut);
        Map<String, Map<String, Object>> data = construireMapInitiale("test");

        // Act
        String evaluation = evaluationExpressionServiceservice.evaluerStringSiExpression(expression, () -> data);

        // Assert
        assertEquals("test", evaluation);
    }
}
```

### PR DESCRIPTION
**Pull request by nicolasguilhem**
* stops visiting tree if JavaSourceFile is not in a package (for Groovy or Kotlin)
* stops visiting tree if JavaSourceFile package is not in a package submited
* do not add link if JavaType is primitive
* add link for generic type with bounds
* added DataTable to list excluded JavaSourceFiles due to package exclusion
* added DataTable to list not handled JavaTypes

/closes #29

### CODE REVIEW

**Review by jtama — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/jtama/openrewrite/ProjectAerialViewGenerator.java [hunk 1]
```diff
@@ -164,13 +157,38 @@ public J preVisit(@NotNull J tree, ExecutionContext ctx) {
...
+                    return;
+                }
+
+                switch (type) {
+                    case JavaType.FullyQualified fq -> addLink(fq);
+                    case JavaType.Array array -> addLink((JavaType.FullyQualified) array.getElemType());
+                    case JavaType.GenericTypeVariable gtv -> gtv.getBounds().stream().forEach(b -> addLinkForType(b));
+                    default -> log.info("Type : " + type + " not handled.");
+                }
+                ;
```
Comment (jtama) [inline src/main/java/io/github/jtama/openrewrite/ProjectAerialViewGenerator.java]: small typo here

**Comment by nicolasguilhem** [comment]
The latest modifications (addition of DataTable) have not been tested because the recipe is no longer found.

File: src/main/java/io/github/jtama/openrewrite/model/JavaSourceFileExcludedReport.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+public class JavaSourceFileExcludedReport extends DataTable<JavaSourceFileExcludedReport.@NotNull Row> {
+
+    public JavaSourceFileExcludedReport(@Nullable Recipe recipe) {
+        super(recipe, "JavaSourceFile excluded",
+                "Records the JavaSourceFile that were not handled by the recipe because it does not match the package list submited.");
+    }
+
+    public static class Row {
+
+        @Column(displayName = "Java source file path", description = "The path of the Java source file that were excluded.")
```
Comment (jtama) [inline src/main/java/io/github/jtama/openrewrite/model/JavaSourceFileExcludedReport.java]:
```suggestion
        @Column(displayName = "Java source file path", description = "The Java source file path that was excluded.")
```

File: src/main/java/io/github/jtama/openrewrite/model/JavaTypesNotHandledReport.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+        super(recipe, "JavaType not handled",
+                "Records the JavaTypes that were not handled by the recipe.");
+    }
+
+    public static class Row {
+
+        @Column(displayName = "Java type class name", description = "The name of the classe representing the JavaType not handled.")
+        String className;
+
+        @Column(displayName = "Java type", description = "The Java Type not handled.")
```
Comment (jtama) [inline src/main/java/io/github/jtama/openrewrite/model/JavaTypesNotHandledReport.java]:
```suggestion
        @Column(displayName = "Java type", description = "The unhandled Java Type.")
```

File: src/main/java/io/github/jtama/openrewrite/ProjectAerialViewGenerator.java [hunk 4]
```diff
@@ -33,10 +33,7 @@
 
 import com.fasterxml.jackson.databind.ObjectMapper;
 
-import io.github.jtama.openrewrite.model.Link;
-import io.github.jtama.openrewrite.model.LinksReport;
-import io.github.jtama.openrewrite.model.Node;
-import io.github.jtama.openrewrite.model.NodesReport;
+import io.github.jtama.openrewrite.model.*;
```
Comment (jtama) [inline src/main/java/io/github/jtama/openrewrite/ProjectAerialViewGenerator.java]: I try to use explicit imports

**Review by jtama — CHANGES_REQUESTED** [review]

**Review by jtama — APPROVED** [review]
LGTM !

@all-contributors, please add @nicolasguilhem  for code !

**Comment by jtama** [comment]
@all-contributors, please add @nicolasguilhem for code !
